apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ngnix-resolver
  name: ngnix-resolver
spec:
  containers:
  - image: ngnix
    name: ngnix-resolver
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
