apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-yaron
spec:
  containers:
  - name: redis-storage-taron
    image:  redis:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - mountPath: /data/redis
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
