apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: use-pv
  name: use-pvspec-yaron
spec:
  containers:
  - name: use-pv
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: "/data"
        name: pv-1
  volumes:
    - name: pv-1
      persistentVolumeClaim:
        claimName: pv-1
  dnsPolicy: ClusterFirst
  restartPolicy: Always

status: {}