apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-nslookup
  name: test-nslookup
spec:
  containers:
  - image: busybox:1.28
    name: test-nslookup
    resources:   
      limits:
        memory: "128Mi"
        cpu: "500m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
