apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ngnix-resolver
  name: ngnix-resolver
spec:
  containers:
  - image: nginx:1.17
    name: ngnix-resolver
    resources:   
      limits:
        memory: "128Mi"
        cpu: "500m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
