apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: alpha
  name: alpha
  env:
    - name: name
      value: alpha
spec:
  containers:
  - image: nginx
    name: alpha
    resources:   
      limits:
        memory: "128Mi"
        cpu: "500m"
  - image: busybox
    name: beta
    resources:   
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["sleep", "4800"]
    env:
    - name: name
      value: beta
  dnsPolicy: ClusterFirst
  restartPolicy: Always

status: {}
